remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dark
title: "Yvidge"
include: ["_pages"]


plugins:
  - jekyll-include-cache
  
sass:   
  load_paths:
    - _sass
    - _site/assets/css
    - _site/assets/css

# Liquid
liquid:
  error_mode: strict

#teaser: assets/images/CuteIso.png
teaser: assets/images/GameDevDeadge.jpg

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/


defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: false

   # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

   # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true